# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e91e4c591c8c671fd1ed9996987edc2f6d8be0364f5075ba99a91099d8b94a20ab60f673af0f711e235f973fbaf6164c424c91ba5ab3e8e7b255a2da3a405db1

test:
  secret_key_base: b14b81fd4c012a49abdb87dd58b52985e9362a74ea61f3632b780c2ccc2efbf3ff3051baf56754fc34f39805c189a2c4fec3be1baa00183722c4254561570e4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
